
import Link from 'next/link';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={geistSans.className}
      >
        {children}
        <Link href="/secret">
          <div className="peeling-corner"></div>
        </Link>
        <footer className={`${geistMono.className}  fixed bottom-0 left-0 w-full p-4 text-center text-xs text-gray-500`}>
          <p>This project is fully vibe coded and deserves no credit.</p>
        </footer>
      </body>
    </html>
  );
}

